// phorport/explore.rs — the FRF-Fuzz counterexample-engine bridge
//
// Phase 4's counterexample engine is **frf-fuzz**, not a local loop. This module
// generates a frf-fuzz differential target around the comparison harness, seeds it
// with the design corpus, runs a bounded campaign, and turns each finding into a
// durable, minimized counterexample.
//
// The target deliberately **panics on divergence**: a differential mismatch is a
// worker-level failure, so frf-fuzz's crash ledger reproduces the exact input, its
// scheduler promotes it to a finding, and `replay`/`tmin` operate on it unchanged.
//
// The generated project is a build artifact (gitignored). It depends on `frf-fuzz`
// (`target-runtime` only, so the coordinator tree never enters the target) and on
// this crate; the external engine is located by path, exactly as the Phase 0
// baseline locates the sibling repositories.

use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::process::Command;

use phost::porting::target::{cases_for, PortTarget};

use crate::case::encode_args;
use crate::config::HarnessConfig;
use crate::counterexample::{self, Counterexample};
use crate::harness::probe;
use crate::minimize;

/// The generated fuzz-target source.
const TARGET_SRC: &str = r#"// Generated by phorport — the frf-fuzz differential harness for a Phorensicos port.
//
// A valid case that diverges from the foreign oracle is a worker-level failure, so
// frf-fuzz's crash ledger reproduces the exact input and its scheduler promotes it
// to a finding. The structural residual is carried in the panic message.
use frf_fuzz::target_runtime::{FuzzContext, SignalId};

const VALID: SignalId = SignalId(0);
const MATCH: SignalId = SignalId(1);
const DIST: SignalId = SignalId(2);

frf_fuzz::fuzz_target!(
    setup = |cx: &mut FuzzContext| {
        cx.register_signal(VALID, "valid_case", "bool")?;
        cx.register_signal(MATCH, "matches_oracle", "bool")?;
        cx.register_signal(DIST, "observable_distance", "units")?;
        Ok(())
    },
    execute = |data: &[u8], cx: &mut FuzzContext| {
        let o = phorport::harness::probe_env(data);
        cx.observe_u64(VALID, o.valid as u64)?;
        cx.observe_u64(MATCH, o.matched as u64)?;
        cx.observe_u64(DIST, o.distance % 1_000_000)?;
        if o.valid && !o.matched {
            panic!(
                "phorensic differential mismatch: {} oracle={} candidate={}",
                o.residual, o.oracle_hex, o.candidate_hex
            );
        }
        Ok(())
    },
);
"#;

/// A bounded campaign outcome.
#[derive(Clone, Debug)]
pub struct CampaignOutcome {
    pub target: String,
    pub findings: u64,
    pub campaign_log: String,
    pub counterexample: Option<Counterexample>,
}

/// Where the generated project lives for a target.
pub fn project_dir(fuzz_root: &Path, name: &str) -> PathBuf {
    fuzz_root.join(name)
}

/// Write the frf-fuzz differential target project.
pub fn generate_project(
    dir: &Path,
    frf_fuzz_root: &Path,
    phorport_root: &Path,
    name: &str,
) -> io::Result<()> {
    let bin_dir = dir.join("src/bin");
    fs::create_dir_all(&bin_dir)?;
    let cargo = format!(
        "[package]\nname = \"phorport-fuzz-{name}\"\nversion = \"0.0.0\"\nedition = \"2021\"\n\n[workspace]\n\n[dependencies]\nfrf-fuzz = {{ path = \"{}\", default-features = false, features = [\"target-runtime\"] }}\nphorport = {{ path = \"{}\" }}\n\n[[bin]]\nname = \"frf_fuzz_{name}\"\npath = \"src/bin/frf_fuzz_{name}.rs\"\n",
        frf_fuzz_root.display(),
        phorport_root.display()
    );
    fs::write(dir.join("Cargo.toml"), cargo)?;
    fs::write(bin_dir.join(format!("frf_fuzz_{name}.rs")), TARGET_SRC)?;
    Ok(())
}

/// Write the design corpus as a frf-fuzz seed corpus, returning the directory.
pub fn write_seeds(dir: &Path, target: &PortTarget) -> io::Result<PathBuf> {
    let seeds = dir.join("seeds");
    fs::create_dir_all(&seeds)?;
    for (i, case) in cases_for(target).iter().enumerate() {
        let data = encode_args(target, &case.args);
        fs::write(seeds.join(format!("{i:04}")), data)?;
    }
    Ok(seeds)
}

fn run(cmd: &mut Command) -> io::Result<(bool, String)> {
    let out = cmd.output()?;
    let mut text = String::from_utf8_lossy(&out.stdout).into_owned();
    text.push_str(&String::from_utf8_lossy(&out.stderr));
    Ok((out.status.success(), text))
}

fn last_findings(log: &str) -> u64 {
    let mut best = 0u64;
    for line in log.lines() {
        if let Some(pos) = line.find("findings=") {
            let rest = &line[pos + "findings=".len()..];
            let digits: String = rest.chars().take_while(|c| c.is_ascii_digit()).collect();
            if let Ok(n) = digits.parse::<u64>() {
                best = best.max(n);
            }
        }
    }
    best
}

/// Extract the first finding id from `frf-fuzz report --json`.
fn first_finding_id(json: &str) -> Option<String> {
    let marker = "\"findings\":[";
    let start = json.find(marker)? + marker.len();
    let rest = &json[start..];
    let idmark = "\"id\":\"";
    let s = rest.find(idmark)? + idmark.len();
    let id: String = rest[s..]
        .chars()
        .take_while(|c| c.is_ascii_hexdigit())
        .collect();
    if id.len() == 64 {
        Some(id)
    } else {
        None
    }
}

/// Extract the input hex from `frf-fuzz replay`.
fn replay_input(log: &str) -> Option<Vec<u8>> {
    for line in log.lines() {
        if let Some(pos) = line.find("input hex: ") {
            let hex = line[pos + "input hex: ".len()..].trim();
            return hex::decode(hex).ok();
        }
    }
    None
}

/// Run a bounded FRF-Fuzz campaign against a defective candidate object.
///
/// `frf_fuzz_bin` is the engine binary; `frf_fuzz_root` its repository (for the
/// generated project's dependency path); `phorport_root` this crate's directory.
#[allow(clippy::too_many_arguments)]
pub fn campaign(
    config: &HarnessConfig,
    target: &PortTarget,
    name: &str,
    fuzz_root: &Path,
    frf_fuzz_root: &Path,
    phorport_root: &Path,
    frf_fuzz_bin: &Path,
    max_time: u64,
    out_dir: &str,
) -> io::Result<CampaignOutcome> {
    let dir = project_dir(fuzz_root, name);
    generate_project(&dir, frf_fuzz_root, phorport_root, name)?;
    let seeds = write_seeds(&dir, target)?;
    let envs = config.env_pairs();

    let (ok, build_log) = run(Command::new(frf_fuzz_bin)
        .args(["build", name])
        .current_dir(&dir)
        .envs(envs.iter().map(|(k, v)| (*k, *v))))?;
    let mut log = build_log;
    if !ok {
        return Err(io::Error::other(format!(
            "frf-fuzz build {name} failed:\n{log}"
        )));
    }

    let (_, run_log) = run(Command::new(frf_fuzz_bin)
        .args([
            "run",
            name,
            "--workers",
            "2",
            "--max-time",
            &max_time.to_string(),
            "--seed-dir",
            seeds.to_str().unwrap_or("seeds"),
        ])
        .current_dir(&dir)
        .envs(envs.iter().map(|(k, v)| (*k, *v))))?;
    log.push_str(&run_log);
    let findings = last_findings(&run_log);

    // Obtain one concrete counterexample from the store and minimize it.
    let mut counterexample = None;
    if findings > 0 {
        let (_, report) = run(Command::new(frf_fuzz_bin)
            .args(["report", "--json"])
            .current_dir(&dir))?;
        if let Some(id) = first_finding_id(&report) {
            let (_, replay) = run(Command::new(frf_fuzz_bin)
                .args(["replay", &id, "--target", name])
                .current_dir(&dir))?;
            if let Some(input) = replay_input(&replay) {
                let outcome = probe(config, &input);
                if outcome.valid && !outcome.matched {
                    let m = minimize::minimize(config, &input, &outcome);
                    let cx = Counterexample::from_minimization(
                        &config.target_id,
                        &config.candidate_path,
                        &config.candidate_hash,
                        &outcome.oracle_hex,
                        &outcome.candidate_hex,
                        &m,
                    );
                    counterexample::write(out_dir, &cx)?;
                    counterexample = Some(cx);
                }
            }
        }
    }

    Ok(CampaignOutcome {
        target: config.target_id.clone(),
        findings,
        campaign_log: log,
        counterexample,
    })
}

/// A convenience: does the design corpus alone already reject this candidate?
///
/// This is how Gate E is stated precisely — a defect the design corpus *misses*
/// is one for which every design case matches the oracle.
pub fn design_corpus_matches(config: &HarnessConfig, target: &PortTarget) -> (u64, u64) {
    let mut ran = 0u64;
    let mut diverged = 0u64;
    for case in cases_for(target) {
        let data = encode_args(target, &case.args);
        let o = probe(config, &data);
        if o.valid {
            ran += 1;
            if !o.matched {
                diverged += 1;
            }
        }
    }
    (ran, diverged)
}
